---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xqxevaho/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp -R .[^.]* $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -R .env $DEPLOYPATH/ 2>/dev/null || true
    - cd $DEPLOYPATH
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan migrate --force
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod -R 777 $DEPLOYPATH/storage
    - /bin/chmod -R 777 $DEPLOYPATH/bootstrap/cache
